excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://rmdrimmie.github.io
title: Hi, my name is Rob Drimmie
tagline: 
description: I like to write about my life, but it's been a long time since I've done so regularly. I'm re-establishing the habit, irregularly and poorly.
paginate: 5
